name: encrypted_social_media_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # utility packages
  http: ^1.1.0
  intl: ^0.19.0
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_localizations:
    sdk: flutter

  # state management
  get: ^4.6.5
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true # Add this line to enable Material Design

  assets:
    - assets/logos/app_logo-removebg.png
    - assets/images/profile_image.jpg
    - assets/images/profile_image_1.jpg
    - assets/images/profile_image_2.jpg
    - assets/images/profile_image_3.jpg
    - assets/images/profile_image_4.jpg
    - assets/images/profile_image_5.jpg
    - assets/images/profile_image_6.jpg
    - assets/images/profile_image_7.webp
    - assets/icons/vip_mode.png
    - assets/icons/free_mode.png

  #-------------------------- local fonts --------------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
flutter_intl:
  enabled: true
